source 'https://rubygems.org'

gem 'facets',                                                    '~> 3.1'
gem 'hiera-eyaml',                                               '~> 2.1'
gem 'json',                                                      '~> 2.1'
gem 'nokogiri',                                                  '~> 1.8'
gem 'onceover-codequality',                                      '~> 0.3'
gem 'onceover',                                                  '>= 3.11.1'
gem 'puppet-lint-classes_and_types_beginning_with_digits-check', '~> 0.1'
gem 'puppet-lint-leading_zero-check',                            '~> 0.1'
gem 'puppet-lint-legacy_facts-check',                            '~> 0.0.3'
gem 'puppet-lint-top_scope_facts-check',                         '~> 0.0.1'
gem 'puppet-lint-trailing_comma-check',                          '>= 0.4.1', '< 1.0.0'
gem 'puppet-lint-unquoted_string-check',                         '~> 1.0'
gem 'puppet-lint-variable_contains_upcase',                      '~> 1.2'
gem 'puppet-lint-version_comparison-check',                      '~> 0.2'
gem 'puppet-lint',                                               '~> 2.3.5'
gem 'puppet-syntax',                                             '~> 2.4'
gem 'puppet',                                                    '~> 6.0'
gem 'puppetlabs_spec_helper',                                    '~> 2.11'
gem 'rest-client',                                               '~> 2.0'
gem 'rspec-puppet',                                              '>= 2.7.3', '< 3.0.0'
gem 'toml-rb',                                                   '1.1.2'
gem 'yamllint',                                                  '~> 0.0.9'
gem 'cri',                                                       '2.15.3'
